### ISSUE TITLE
Not working on Win10

### ISSUE THREAD

**Issue by geekgao** [PerfectLaugh/wg-windivert#1]
Hi, author, I don't know if you still maintain this project. After deploying it on the Windows 10 Pro x64 platform, I found that it does not work. No error messages were reported, but it seems that the TUN device was not created, and the network access of the injected process timed out.

**Comment by PerfectLaugh** [comment]
Unfortunately I didn't maintain this project anymore. I just use commercial game accelerator like UU booster.
This project suffers couple of problems from WinDivert driver which is also not maintained, including erroneous connection handling mechanism (packets could come first while connection is not notified opening).

I suggest you not to use this project, or try help me improve it somehow :(

**Comment by geekgao** [comment]
Thank you for your reply. I have little experience with wintun and am unable to help to the project.
